mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb_db
  config: charset=utf8mb4&parseTime=True
  user: root
  password: 1310138359
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 127.0.0.1
  port: 8080
  env: dev