mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: gvb_db
  user: root
  password: "1310138359"
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 127.0.0.1
  port: 8080
  env: release
local_upload:
  upload_file_path: uploads/file
  size: 2
site_info:
  created_at: "2024-05-01"
  bei_an: 鲁ICP备2024080111号-1
  title: 邓智超的个人博客
  qq_image: ""
  version: 1.0.0
  email: zhichaodeng2023@163.com
  wechat_image: ""
  name: 邓智超
  job: golang
  addr: 现居浙江杭州
  slogan: 冲冲冲
  slogan_en: fighting!
  web: http://www.baidu.com
  bilibili_url: 小超同学dz
  gitee_url: ""
  github_url: zhichao2000
qq:
  app_id: ""
  key: ""
  redirect: ""
email:
  host: smtp.qq.com
  port: 213
  user: 1310138359@qq.com
  password: xxx
  default_from_email: 智超知道
  use_ssl: false
  user_tls: true
qiniu:
  enable: false
  access_key: N3u3KYmFb4J35SaUt_m1GIG5Ndl-EQjHY3MFnXnN
  secret_key: efi-XifczQfesM2plHKj-sKRjOu8DEgoXGcnZZIv
  bucket: chaochaozhidao
  cdn: qiniu.cdn.dzcs.online
  zone: z0
  size: 4
jwt:
  secret: dengzhichao
  expires: 30
  issuer: xxx
